project:
  type: website
  output-dir: docs

website:
  title: "Apple watch fitness dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: general.qmd
        text: General statistics

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
